main: org.hexic.playermines.Main
name: PlayerMines
version: 0.6.4
api-version: 1.18
author: Hexic
depend: [FastAsyncWorldEdit, WorldBorderAPI, WorldGuard, JetsPrisonMines, UltraPrisonCore]
description: Ability to create a private mine per player.
commands:
  PlayerMine:
    aliases: [pmine, plm]