main: org.hexic.playermines.PlayerMines
name: PlayerMines
version: 0.5
api-version: 1.16
author: Hexic
depend:
  - WorldEdit
  - WorldBorderAPI
  - WorldGuard
  - JetsPrisonMines
  - UltraPrisonCore
description: Ability to create a private mine per player.
commands:
  PlayerMine:
    aliases: [pmine, plm]